<?php declare(strict_types=1); ?>
<section class="container">
    <div class="home-header">
        <h1><?= $this->translate('project.title'); ?></h1>
        <p><?= $this->translate('project.description'); ?></p>
    </div>
    <section id="threads">
        <div class="row">
            <div class="col-md-6">
                <table class="thread-list table table-striped table-hover">
                    <tbody>
                        <?php foreach ($this->groups as $index => $group) { ?>
                            <tr>
                                <td class="number-of-messages">
                                    <span class="badge badge-default">N/A</span>
                                </td>
                                <td>
                                    <a class="thread-subject" href="/<?= $this->escape(rawurlencode($group->getName())); ?>"><?= $this->escape($group->getName()); ?></a>
                                    <br class="visible-xs">
                                    <small class="text-muted">
                                        <?php if ($group->getNumberOfThreads()) { ?>
                                            <time-ago datetime="<?= $group->getTimestamp()->format('c'); ?>"><?= $group->getTimestamp()->format('M j, Y'); ?></time-ago>
                                            -
                                            <?= $this->translate('page.groups.overview.group.threads.%', [$group->getNumberOfThreads()]); ?>
                                        <?php } else { ?>
                                            <?= $this->translate('page.groups.overview.group.empty'); ?>
                                        <?php } ?>
                                    </small>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <?php if (count($this->latest)) { ?>
                    <h2><?= $this->translate('page.groups.overview.latest.title'); ?></h2>
                    <table class="thread-list table table-striped table-hover">
                        <tbody>
                            <?php foreach ($this->latest as $article) { ?>
                                <tr>
                                    <td>
                                        <a class="thread-subject" href="/">Thread name here</a>
                                        <br class="visible-xs">
                                        <small class="text-muted">
                                            <time-ago datetime="<?= $article->getTimestamp()->format('c'); ?>"><?= $article->getTimestamp()->format('M j, Y'); ?></time-ago>
                                            -
                                            <?= $this->escape($article->getAuthorName()); ?>
                                        </small>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <?php } ?>
                <h2>Todo</h2>
                <p>Filters / search/ last messages here?</p>
            </div>
        </div>
    </section>
</section>
