<?php declare(strict_types=1); ?>
<div class="container">
    <div class="home-header">
        <h1><?= $this->translate('project.title'); ?></h1>
        <p><?= $this->translate('project.description'); ?></p>
    </div>
    <section id="threads">
        <table class="thread-list table table-striped table-hover">
            <tbody>
                <?php foreach ($this->groups as $group) { ?>
                    <tr>
                        <td class="number-of-messages">
                            <span class="badge badge-default">N/A</span>
                        </td>
                        <td>
                            <a class="thread-subject" href="/design/thread"><?= $this->escape($group->getName()); ?></a>
                            <br class="visible-xs">
                            <small class="text-muted">
                                2 hours ago
                                - 12 emails
                            </small>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
