<?php declare(strict_types=1); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $this->translate('project.title'); ?></title>
        <link href="/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <?= $content; ?>
        <script src="/js/jquery-1.12.4.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </body>
</html>
