<?php declare(strict_types=1); ?>
<section class="container">
    <div class="home-header">
        <h1><?= $this->escape($this->group); ?></h1>
    </div>
    <section id="threads">
        <div class="row">
            <div class="col-md-12">
                <table class="thread-list table table-striped table-hover">
                    <tbody>
                        <?php foreach ($this->threads as $index => $thread) { ?>
                            <tr>
                                <td class="number-of-messages">
                                    <span class="badge badge-default">N/A</span>
                                </td>
                                <td>
                                    <a class="thread-subject" href="/<?= $this->escape(rawurlencode($thread->getSubject())); ?>"><?= $this->escape($thread->getSubject()); ?></a>
                                    <br class="visible-xs">
                                    <small class="text-muted">
                                        <?php if ($thread->getNumberOfMessages()) { ?>
                                            <time-ago datetime="<?= $thread->getTimestamp()->format('c'); ?>"><?= $thread->getTimestamp()->format('M j, Y'); ?></time-ago>
                                            -
                                            <?= $this->translate('page.threads.overview.thread.messages.%', [$thread->getNumberOfMessages()]); ?>
                                        <?php } else { ?>
                                            <?= $this->translate('page.threads.overview.thread.empty'); ?>
                                        <?php } ?>
                                    </small>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</section>
